<?php
/**
 * @file
 * Special users are an experimental feature of P2
 * allowing for users to be tagged into groups like
 * "Ambassadors" or "This weeks user" or "Our favorite authors"
 * A taxonomy is introduced for this.
 * A term reference field is introduced to the user entity.
 * Some views implements these groups of tagged users.
 */

include_once 'ding_special_user.features.inc';

/**
 * Implements hook_user_complete().
 */
function ding_special_user_ding_user_complete() {
  global $user;
  /*
  // Not in p2
  $profile = profile2_load_by_user($user, 'special_user');
  return array(
    'ding_special_user' => array(
      'title' => 'Ding special user',
      'points' => 4,
      'completed' => (isset($profile) && !empty($profile->field_list_image)),
      'markup' => t('Upload an image to your special user profile.'),
    ),
  );
  */
}

